server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: docker_logs
  # pipeline_stages:
  # - docker:
  static_configs:
  - targets:
    - localhost
    labels:
      job: docker_logs_1
      __path__: /logs/*.log
  # pipeline_stages:
  
  

  # - json:
  #   expressions:
  #     time:
  # - regex:
  #     expression: "^(?P<year>\\d+)"
  #     source:     "time"


    # - match:
    #   selector: '{name="nginx"} |= "GET"'
    #   stages:
    #   # This regex stage extracts a new output by matching against some
    #   # values and capturing the rest.
    #   - regex:
    #     expression: \w{1,3}.\w{1,3}.\w{1,3}.\w{1,3}(?P<output>.*)

    #   # The output stage changes the content of the captured log line by
    #   # setting it to the value of output from the regex stage.
    #   - output:
    #     source: output



# - job_name: system
#   static_configs:
#   - targets:
#     - localhost
#     labels:
#       job: varlogs
#       __path__: /var/log/*log
